console.log("Rodando o sistema de gerenciamento de jogos")
console.log("Aplicação está se conectando ao banco de dados")
console.log("Exibindo a lista de jogos")
console.log("Exibindo o jogo selecionado")
console.log("Enviando para o GitHub")
